### ISSUE TITLE
add support for single-valued fields

### ISSUE THREAD

**Issue by twpayne** [muesli/combinator#1]
Firstly, thank you for this awesome module! It's really helpful and has both reduced the amount of test code that I have to write and increased my test coverage :)

I have a sum type switched on a field:

```go
type T struct {
	IsIntsNotStrings bool
	Ints             []int
	Strings          []string
}
```

Depending on the value of `IsIntsNotStrings`, either `Ints` or `Strings` will be filled, but never both.

I can use `muesli/combinator` to generate a bunch of combinations like this:

```go
var ts []T
combinator.Generate(&ts, struct {
	IsIntsNotStrings []bool
	Ints             []int
	Strings          []string
}, {
	IsIntsNotStrings: []bool{true},
	Ints:             []int{1, 2, 3},
})
combinator.Generate(&ts, struct {
	IsIntsNotStrings []bool
	Ints             []int
	Strings          []string
}, {
	IsIntsNotBools: []bool{false},
	Strings:        []string{"a", "b", "c"},
})
```

Thanks to `combinator`'s appending of options, I end up with a nice test suite, but I have to use arrays with one element for `IsIntsNotStrings` and add fields to my `struct` that always take the zero value in my test data.

What I would like to write is this:

```go
var ts []T
combinator.Generate(&ts, struct {
	IsIntsNotStrings bool
	Ints             []int
}, {
	IsIntNotStrings: true,
	Ints:            []int{1, 2, 3},
})
combinator.Generate(&ts, struct {
	IsIntsNotStrings bool
	Strings          []string
}, {
	IsIntsNotStrings: false,
	Strings:          []string{"a", "b", "c"},
})
```

What changed:

* There is less code.
* `IsIntsNotBool` changed from a slice of `[]bool` to a single-valued `bool`, with only that single value used to generate combinations.
* `Ints` and `Strings` are only specified if their values change, otherwise the zero value is used.

(apologies for any errors in the above code - it was a manually simplified example and may contain errors, but I hope the intent is clear)

**Comment by muesli** [comment]
That's a fantastic idea @twpayne! Let me quickly try to implement that!

As a side-note, you don't actually need to specify any fields in the temporary generator struct that you don't end up using. For example you can skip declaring `Strings` in this example, even if `Strings` is a member of generated structs of type `T`:

```go
var ts []T
combinator.Generate(&ts, struct {
	IsIntsNotStrings []bool
	Ints             []int
}, {
	IsIntsNotStrings: []bool{true},
	Ints:             []int{1, 2, 3},
})
```

It will only return an error if you've declared a field that doesn't exist in `T`.

**Comment by twpayne** [comment]
Thank you very much for the speedy fix :)

Would you mind tagging a new release?

**Comment by muesli** [comment]
Of course!

v0.3.0: https://github.com/muesli/combinator/releases/tag/v0.3.0
